### ISSUE TITLE
Decide where to store project sponsor logos

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1454]
Following on from #1399; requesting discussion from @kimrutherford and @barnabynorman.

- - -

I've created resized versions of all the sponsor logos for PHI-base. Here's how they look in the browser (Chrome):

![project_specific_logos](https://user-images.githubusercontent.com/37659591/40051388-790fbfc0-5832-11e8-97e7-65ec8976929c.PNG)

Now we have to decide where to store the logo image files, and how to reference them in `canto_deploy.yaml`.

@kimrutherford I tried to store the logos outside of the Canto directory like you suggested, and referenced them using file URIs (see example below) but the app couldn't locate the images.

```yaml
# did not work
extra_sponsors:
  - link_url: "https://bbsrc.ukri.org/"
    logo_url: "file:///home/canto/logos/bbsrc_logo.png"
```
So my current thinking is that we should add an ignored sub-directory within `/static/images/`, named something like `extra_sponsors` or `sponsor_logos`, and then reference that with relative paths in `canto_deploy.yaml`:

```yaml
# works correctly
extra_sponsors:
  - link_url: "https://bbsrc.ukri.org/"
    logo_url: "/static/images/extra_sponsors/bbsrc_logo.png"
```
To make it more user-friendly, we could add a `README.md` to the `extra_sponsors` directory (and ignore everything _except_ the README file) for two reasons:

- to make it obvious what the directory is for, and
- to allow the directory to be checked out when there are no sponsor logos added to it.

I'm open to suggestions. If we decide to go with the sub-directory option, I'll open a pull request to make the changes.
