### ISSUE TITLE
Canto fails to read PHIPO annotation types from server

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1475]
After adding new phenotype annotation types (from PHIPO) to the `canto_deploy.yaml`, I get error messages on the curation summary page, for example: “Error for disease formation phenotype: couldn't read annotations from the server - please try reloading”

![phipo_phenotypes_server_error](https://user-images.githubusercontent.com/37659591/40659664-d8dc602e-6346-11e8-9c86-d9bd3edaf31b.PNG)

**Comment by kimrutherford** [comment]
Could you check the console to see if there are any errors or stack traces from the Perl code?

**Comment by jseager7** [comment]
There aren't any errors; all I see in the console when loading the curation summary is this, three times:

`Reference passed to set at /usr/local/share/perl/5.26.1/Cache.pm line 293.`

I'm not in debug mode, by the way. Would that help?

**Comment by kimrutherford** [comment]
> Reference passed to set at /usr/local/share/perl/5.26.1/Cache.pm line 293.

That's a internal warning from one of the dependencies.  As far as I can tell it's harmless.

> I'm not in debug mode, by the way. Would that help?

Error should be displayed even when not in debug mode.

Could you try looking in the network tab in the developer tools and check for any URLs like:
  http://localhost:7005/curs/7aced580db8cb1de/ws/annotation/list/phenotype?u=1528008269570

The "phenotype" will change depending on which phenotype it's trying to fetch.

If you look at the responses for those requests for you should see the error(s) from the server.

**Comment by jseager7** [comment]
Thanks for reminding me about this, but I can't seem to reproduce the error now. I've changed my `canto_deploy.yaml` so it has the following annotation types loaded (I've omitted some properties):

```yaml
available_annotation_types:
  - name: phenotype
    category: ontology
    namespace: 'host phenotype'
    very_short_display_name: 'phenotype'
    short_display_name: 'phenotype'
    display_name: 'phenotype'
    synonyms_to_display:
      - exact
    feature_type: 'genotype'
    ...
  - name: phenotype
    category: ontology
    namespace: 'pathogen phenotype'
    very_short_display_name: 'phenotype'
    short_display_name: 'phenotype'
    display_name: 'phenotype'
    synonyms_to_display:
      - exact
    feature_type: 'genotype'
    ...
  - name: phenotype
    category: ontology
    namespace: 'disease formation phenotype'
    very_short_display_name: 'phenotype'
    short_display_name: 'phenotype'
    display_name: 'phenotype'
    synonyms_to_display:
      - exact
    feature_type: 'genotype'
    ...
```
But I'm not sure if that's the right approach to load multiple phenotype annotation types. Presumably the property names have to be `phenotype`, but won't that cause a problem with duplicate keys?

Either way, I'm not seeing the error messages on the summary page, but then again I haven't made any phenotype annotations (and I'm unable to create any, because the phenotype suggestion field can't read the terms from PHIPO). So maybe the last time I did this I already had some phenotype annotations created before I switched the phenotype ontology to PHIPO... not sure.

Anyway, with regards to the annotation webservice, all I get back from the following address is an empty array.

`http://localhost:5000/curs/7796b96c6bffdaf4/ws/annotation/list/phenotype?u=1530007142646`

**Comment by jseager7** [comment]
I happened to notice something else while I was trying to reproduce this: I get the same error with all annotation types if I happen to navigate back to the summary page while Canto is not running: I can still load the page, but all of the webservices (obviously) fail.

So, it might have been an oversight on my part not realising that I hadn't restarted the server the first time, but I'm still not certain.

**Comment by kimrutherford** [comment]
Hi James.

Sorry I wasn't more clear.  The "name" of each annotation type needs to be unique as the annotation type get stored in a map internally and the name is the key.  The name is also what appears in web service URLs so it's probably best if it has no spaces.  So try something like:

```yaml
available_annotation_types:
  - name: host_phenotype
    category: ontology
    namespace: 'host phenotype'
...
```
