### ISSUE TITLE
Reconfigure PHI-Canto to use new email address

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1507]
Now that PHI-Canto has a dedicated email address, we need to change the Canto configuration and the server configuration to point at the new address: `curation@phi-base.org`.

@barnabynorman will need to update the server settings so that `curation@phi-base.org` will be the main address (instead of `contact@phi-base.org`).

The configuration changes will be handled by a separate commit in [PHI-base/config](https://github.com/PHI-base/config/), but these are the properties that will have to change:

```yaml
email:
  from_address:    contact@phi-base.org
  admin_address:   contact@phi-base.org
  noreply_address: contact@phi-base.org
```
