### ISSUE TITLE
Allow absolute paths to email templates

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1535]
The email templates in root/email_templates/ aren't suitable for PHI-Canto.  We can either add PHI-Canto templates in a separate sub-directory or allow absolute paths so they can be stored anywhere in the file system.

This might help: https://metacpan.org/pod/release/DROLSKY/HTML-Mason-1.58/lib/HTML/Mason/Interp.pm#comp_root

**Comment by kimrutherford** [comment]
I've added an extra setting in the `email` section of the config.  You can now set `template_root` to point to the location of your email templates, which can be anywhere in the file system.

You'll need to copy the `canto/root/email_templates` directory somewhere for editing.  Perhaps it makes sense to create a `phi-canto-config` GitHub repo for things like this?

If you haven't done it already, you'll need to copy this section from `canto.yaml` and edit it appropriately.  Please let me know if I can help with that.

```yaml
 email:
   from_address: CONFIGURE_ME_IN_CANTO_DEPLOY.YAML
   admin_address: CONFIGURE_ME_IN_CANTO_DEPLOY.YAML
   noreply_address: CONFIGURE_ME_IN_CANTO_DEPLOY.YAML
   template_root: "/some/absolute/path/"
   templates:
     session_accepted:
       subject: "email_templates/generic/session_accepted_subject.mhtml"
       body: "email_templates/generic/session_accepted_body.mhtml"
     session_assigned:
       # Set the "From" to be the current, logged in admin user to make         
       # messages more personal - see SourceForge #604
       from_address: CURRENT_USER
       subject: "email_templates/generic/session_assigned_subject.mhtml"
       body: "email_templates/generic/session_assigned_body.mhtml"
     session_reassigned:
       subject: "email_templates/generic/session_reassigned_subject.mhtml"
       body: "email_templates/generic/session_reassigned_body.mhtml"
     session_resent:
       from_address: CURRENT_USER
       subject: "email_templates/generic/session_resent_subject.mhtml"
       body: "email_templates/generic/session_resent_body.mhtml"
     reassigner:
       subject: "email_templates/generic/reassigner_subject.mhtml"
       body: "email_templates/generic/reassigner_body.mhtml"
     daily_summary:
       global: 1  # not an email about a particular session/publication
       subject: "email_templates/generic/daily_summary_subject.mhtml"
       body: "email_templates/generic/daily_summary_body.mhtml"
```
