### ISSUE TITLE
Add PHI-Canto specific guidance to finish_form

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1660]
We need to add additional information to the finish form to provide guidance to curators that is more specific to PHI-base's needs, in the case where the curator cannot curate certain data.

This text can presumably be configured by adding a `finish_form` property to the `canto_deploy` file. There are two properties that can be set:

### `extra_text`

This text is **always shown** on the finish form. The default Pombase version is as follows:

> If there is any information in your paper which you could not capture in the curation tool, please describe the data briefly, as the curators may be able to include it in the database.

### `extra_text_gene_information`

This text is only shown if the curator has added **one or more genes** to the session. The default Pombase version is as follows:

> Examples include:
> 
> * protein domain data or other protein sequence features
> * missing gene names (synonyms)
> * transcriptional regulation (of the wild-type allele - transcriptional changes due to mutations can be captured in Canto)
> * complementation data (whether the pombe gene complements a homologue in a different organism or vice versa; complementation may be full, partial or absent)
> * gene product name updates
> * human or budding yeast orthologs

- - -
@kehammond @CuzickA @martin2urban Suggestions are welcome about what needs to be added here.

**Comment by CuzickA** [comment]
suggest remove 'human or budding yeast orthologs'

complementation data (whether the pombe gene complements a homologue in a different organism or vice versa; complementation may be full, partial or absent)

Change above to 
complementation data (whether the gene complements a homologue in a different organism or vice versa; complementation may be full, partial or absent)

**Comment by jseager7** [comment]
@kimrutherford I tried to override the `finish_form` sub-property of `curs_config` in the canto_deploy.yaml, but I'm getting an error from Catalyst. I remember you saying before how Canto doesn't merge properties of the config file if you only override a few of the sub-properties, so I copied the whole of `curs_config` from canto.yaml into canto_deploy.yaml, and made a few necessary changes:

```yaml
curs_config:
  no_genes_reasons:
    - No gene specific data
    - Review
    - HTP data only
    - Methods paper
    - Other
  no_annotation_reasons:
    - Experimental data, not of available types
    - Method
    - Opinion or Comment
    - Review
    - Other
  demo_user_name: Demo User
  demo_user_email_address: "demo@example.com"
  follow_inverse_cv_names:
    - fission_yeast_phenotype
  finish_form:
    extra_text: >
      <p>
        If there is any information in your paper which you could not capture in
        the curation tool, please describe the data briefly, as the
        curators may be able to include it in the database.
      </p>
    extra_text_gene_information: >
      <p>
        Examples include:
        <ul>
        <li> protein domain data or other protein sequence features
        <li> missing gene names (synonyms)
        <li> transcriptional regulation (of the wild-type allele - transcriptional changes due to mutations can be captured in Canto)
        <li> complementation data (whether the pombe gene complements a homologue in a different organism or vice versa; complementation may be full, partial or absent)
        <li> gene product name updates
        <li> human or budding yeast orthologs
        </ul>
        Most of these annotation types will be handled in future releases of the
        curation tool.
      </p>
  genotype_config:
    default_strain_name: 'h+'
```
Unfortunately when I navigate to the 'Curation finished' page, I get the following error in the shell console:

```
Use of uninitialized value $force in string ne at lib/Canto/Curs/State.pm line 324.
Use of uninitialized value $force in concatenation (.) or string at lib/Canto/Curs/State.pm line 326.
NOOP: setting NEEDS_APPROVAL to NEEDS_APPROVAL -
 at lib/Canto/Controller/Curs.pm line 2102.
        Canto::Controller::Curs::finish_form(Canto::Controller::Curs=HASH(0x96f80f0), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst/Action.pm line 65
        Catalyst::Action::execute(Catalyst::Action=HASH(0x99b4b10), Canto::Controller::Curs=HASH(0x96f80f0), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst.pm line 1770
        eval {...} called at /usr/share/perl5/Catalyst.pm line 1770
        Catalyst::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x99b4b10)) called at /usr/share/perl5/Catalyst/Plugin/Authorization/ACL.pm line 39
        Catalyst::Plugin::Authorization::ACL::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x99b4b10)) called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 21
        Catalyst::Plugin::StackTrace::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x99b4b10)) called at /usr/share/perl5/Catalyst/Action.pm line 60
        Catalyst::Action::dispatch(Catalyst::Action=HASH(0x99b4b10), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst/ActionChain.pm line 46
        Catalyst::ActionChain::dispatch(Catalyst::ActionChain=HASH(0xc3c0248), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst/Controller.pm line 161
        Catalyst::Controller::_ACTION(Canto::Controller::Curs=HASH(0x96f80f0), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst/Action.pm line 65
        Catalyst::Action::execute(Catalyst::Action=HASH(0x98e8368), Canto::Controller::Curs=HASH(0x96f80f0), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst.pm line 1770
        eval {...} called at /usr/share/perl5/Catalyst.pm line 1770
        Catalyst::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x98e8368)) called at /usr/share/perl5/Catalyst/Plugin/Authorization/ACL.pm line 39
        Catalyst::Plugin::Authorization::ACL::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x98e8368)) called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 21
        Catalyst::Plugin::StackTrace::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x98e8368)) called at /usr/share/perl5/Catalyst/Action.pm line 60
        Catalyst::Action::dispatch(Catalyst::Action=HASH(0x98e8368), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst/Dispatcher.pm line 258
        Catalyst::Dispatcher::_do_forward(Catalyst::Dispatcher=HASH(0x5c43978), "forward", Canto=HASH(0xc235d18), "_ACTION") called at /usr/share/perl5/Catalyst/Dispatcher.pm line 238
        Catalyst::Dispatcher::forward(Catalyst::Dispatcher=HASH(0x5c43978), Canto=HASH(0xc235d18), "_ACTION") called at /usr/share/perl5/Catalyst.pm line 398
        Catalyst::forward(Canto=HASH(0xc235d18), "_ACTION") called at /usr/share/perl5/Catalyst/Controller.pm line 135
        Catalyst::Controller::_DISPATCH(Canto::Controller::Curs=HASH(0x96f80f0), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst/Action.pm line 65
        Catalyst::Action::execute(Catalyst::Action=HASH(0x98f62f8), Canto::Controller::Curs=HASH(0x96f80f0), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst.pm line 1770
        eval {...} called at /usr/share/perl5/Catalyst.pm line 1770
        Catalyst::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x98f62f8)) called at /usr/share/perl5/Catalyst/Plugin/Authorization/ACL.pm line 39
        Catalyst::Plugin::Authorization::ACL::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x98f62f8)) called at /usr/share/perl5/Catalyst/Plugin/StackTrace.pm line 21
        Catalyst::Plugin::StackTrace::execute(Canto=HASH(0xc235d18), "Canto::Controller::Curs", Catalyst::Action=HASH(0x98f62f8)) called at /usr/share/perl5/Catalyst/Action.pm line 60
        Catalyst::Action::dispatch(Catalyst::Action=HASH(0x98f62f8), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst/Dispatcher.pm line 258
        Catalyst::Dispatcher::_do_forward(Catalyst::Dispatcher=HASH(0x5c43978), "forward", Canto=HASH(0xc235d18), "/curs/_DISPATCH") called at /usr/share/perl5/Catalyst/Dispatcher.pm line 238
        Catalyst::Dispatcher::forward(Catalyst::Dispatcher=HASH(0x5c43978), Canto=HASH(0xc235d18), "/curs/_DISPATCH") called at /usr/share/perl5/Catalyst.pm line 398
        Catalyst::forward(Canto=HASH(0xc235d18), "/curs/_DISPATCH") called at /usr/share/perl5/Catalyst/Dispatcher.pm line 107
        Catalyst::Dispatcher::dispatch(Catalyst::Dispatcher=HASH(0x5c43978), Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst.pm line 1716
        Catalyst::dispatch(Canto=HASH(0xc235d18)) called at /usr/local/share/perl/5.20.2/Catalyst/Plugin/PageCache.pm line 140
        Catalyst::Plugin::PageCache::dispatch(Canto=HASH(0xc235d18)) called at /usr/local/share/perl/5.20.2/Catalyst/Plugin/Static/Simple.pm line 86
        Class::MOP::Class:::around(CODE(0x5f7ba30), Canto=HASH(0xc235d18)) called at /usr/lib/x86_64-linux-gnu/perl5/5.20/Class/MOP/Method/Wrapped.pm line 157
        Class::MOP::Method::Wrapped::__ANON__(Canto=HASH(0xc235d18)) called at /usr/lib/x86_64-linux-gnu/perl5/5.20/Class/MOP/Method/Wrapped.pm line 86
        Canto::dispatch(Canto=HASH(0xc235d18)) called at /usr/share/perl5/Catalyst.pm line 2100
        Catalyst::try {...} () called at /usr/local/share/perl/5.20.2/Try/Tiny.pm line 102
        eval {...} called at /usr/local/share/perl/5.20.2/Try/Tiny.pm line 93
        Try::Tiny::try(CODE(0xc209718), Try::Tiny::Catch=REF(0xbc1f960)) called at /usr/share/perl5/Catalyst.pm line 2109
        Catalyst::handle_request("Canto", "env", HASH(0xc443e40), "response_cb", CODE(0xc24c478)) called at /usr/share/perl5/Catalyst/Engine.pm line 798
        Catalyst::Engine::__ANON__(CODE(0xc24c478)) called at /usr/local/share/perl/5.20.2/Plack/Middleware/HTTPExceptions.pm line 32
        Plack::Middleware::HTTPExceptions::try {...} () called at /usr/local/share/perl/5.20.2/Try/Tiny.pm line 102
        eval {...} called at /usr/local/share/perl/5.20.2/Try/Tiny.pm line 93
        Try::Tiny::try(CODE(0xc2600d0), Try::Tiny::Catch=REF(0xc444230)) called at /usr/local/share/perl/5.20.2/Plack/Middleware/HTTPExceptions.pm line 41
        Plack::Middleware::HTTPExceptions::__ANON__(CODE(0xc221b78)) called at /usr/local/share/perl/5.20.2/Plack/Util.pm line 339
        Plack::Util::__ANON__(CODE(0xc44c6e8)) called at /usr/local/share/perl/5.20.2/Plack/Util.pm line 339
        Plack::Util::__ANON__(CODE(0xc25c550)) called at /usr/local/share/perl/5.20.2/Plack/Util.pm line 339
        Plack::Util::__ANON__(CODE(0xc281788)) called at /usr/local/share/perl/5.20.2/Plack/Util.pm line 339
        Plack::Util::__ANON__(CODE(0xc444d10)) called at /usr/local/share/perl/5.20.2/HTTP/Server/PSGI.pm line 193
        HTTP::Server::PSGI::handle_connection(HTTP::Server::PSGI=HASH(0x9dd58f0), HASH(0xc443e40), IO::Socket::INET=GLOB(0xc29c258), CODE(0x9ddd3e0)) called at /usr/local/share/perl/5.20.2/HTTP/Server/PSGI.pm line 141
        HTTP::Server::PSGI::accept_loop(HTTP::Server::PSGI=HASH(0x9dd58f0), CODE(0x2b0c580)) called at /usr/local/share/perl/5.20.2/HTTP/Server/PSGI.pm line 63
        HTTP::Server::PSGI::run(HTTP::Server::PSGI=HASH(0x9dd58f0), CODE(0x2b0c580)) called at /usr/local/share/perl/5.20.2/Plack/Handler/HTTP/Server/PSGI.pm line 14
        Plack::Handler::HTTP::Server::PSGI::run(Plack::Handler::Standalone=HASH(0x9dcc818), CODE(0x2b0c580)) called at /usr/local/share/perl/5.20.2/Plack/Loader.pm line 84
        Plack::Loader::run(Plack::Loader=HASH(0x9436b08), Plack::Handler::Standalone=HASH(0x9dcc818)) called at /usr/local/share/perl/5.20.2/Plack/Runner.pm line 277
        Plack::Runner::run(Plack::Runner=HASH(0x29d57b0), CODE(0x2b0c580)) called at ./script/canto_start line 133
Use of uninitialized value $force in string ne at lib/Canto/Curs/State.pm line 383.
trying to start approving a session that isn't in the state CURATION_IN_PROGRESS it's currently: NEEDS_APPROVAL at lib/Canto/Controller/Curs.pm line 2102.
```
Is this an error on my part? Does `curs_config` support being overridden in this way?
