### ISSUE TITLE
Fly-canto: eliminate 'evidence code' field from phenotype annotation workflow and table

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1815]
Eliminate 'evidence code' field from Fly-Canto's phenotype annotation workflow and table

FlyBase does not use evidence codes for phenotype annotations

**Comment by kimrutherford** [comment]
Canto also has a experimental conditions selector on the evidence page. Should that be hidden too?

**Comment by kimrutherford** [comment]
Note to self, we also need to hide evidence and conditions in the annotation edit dialog:

![annotation-edit-evidence-1](https://user-images.githubusercontent.com/90474/55431101-2a30e100-55ec-11e9-9348-49be478361f7.png)

**Comment by vmt25** [comment]
> Canto also has a experimental conditions selector on the evidence page. Should that be hidden too?

Yes, please! Thanks

**Comment by kimrutherford** [comment]
I've fixed the code so that if an annotation type has no evidence codes configured, all the evidence interface is hidden and the evidence step in the annotation workflow will be skipped.

For example here's the start of the phenotype config in my test Canto.  Removing the `evidence_codes` section entirely will disable the evidence UI for phenotype annotations:

```
   - name: phenotype
     category: ontology
     namespace: FlyBase_anatomy_CV
     very_short_display_name: 'phenotype'
     short_display_name: 'phenotype'
     display_name: 'phenotype'
     synonyms_to_display:
       - exact
     feature_type: 'genotype'
     can_have_conditions: 0
     evidence_codes:
       - Cell growth assay
       - Chromatin immunoprecipitation experiment
       - Chromatography evidence
     ...
```

And to hide the conditions use this setting: `can_have_conditions: 0`

I've updated the flybase-test Canto.  https://curation.pombase.org/flybase-test
