### ISSUE TITLE
Allow/mark 'accessory' alleles in Fly-Canto

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1828]
Fly-Canto neads the ability to add/mark 'accessory' alleles to genotypes. These are tools instead of objects of research interest and should be marked as such.

The majority of FlyBase's accessory alleles are GAL4 drivers, i.e. yeast's GAL4 under a promoter that drives expression at a given tissue/developmental stage. These 'drivers' allow expression of a transgene under the regulation of UAS sequences

e.g.
elav-GAL4 + UAS-Ras[V12] allows for the expression of RasV12 on the domain of expression of the elav gene.

In this case, Ras[V12] is the object of interest/study whereas elav-GAL4 is the tool for expression. They should be marked differently.

**Comment by kimrutherford** [comment]
I don't think we made a final decision on how to do this.  We discussed the possibility of having a bulk edit system.

**Comment by vmt25** [comment]
> I don't think we made a final decision on how to do this. We discussed the possibility of having a bulk edit system.

uh... I thought we had decided to allow for individual and bulk edit of genotypes

**Comment by kimrutherford** [comment]
> uh... I thought we had decided to allow for individual and bulk edit of genotypes

I'd like to have a chat about how the interface would work for bulk editing and maybe draw a mock-up to check that we're all happy.

PomBase will have a chat about it at our next meeting.

**Comment by vmt25** [comment]
This issues seems to be mostly sorted by having the most likely accessory alleles labelled as 'accessory' on the upload file.

However, it would be necessary to add 'accessory' to the allele type list.
Even better, would it be possible restrict Fly-Canto allele type list to 'aberration', 'accessory' and 'other'?

**Comment by vmt25** [comment]
1. For @gm119 and @vmt25: come up with a better name for 'other' alleles (e.g. 'experimental'?, 'conventional'?)

2.
> Even better would be to restrict Fly-Canto allele type list to 'aberration', 'accessory', 'other' and maybe 'wild-type'?, which seem to be the only ones needed at this point.
After second thought, it would be even better to only allow for 'other' and 'accessory' on the edit and copy/edit allele type menus.

3. Only show allele type between parenthesis for accessory' alleles (as per Tuesday's discussion).

**Comment by vmt25** [comment]
This ticket (#1828) is part of #976

**Comment by kimrutherford** [comment]
>After second thought, it would be even better to only allow for 'other' and 'accessory' on the edit and\
> copy/edit allele type menus.

That makes sense.  So the `allele_type_list` config would be:

```yaml
- name: other
  export_type: other
  show_description: false
  description_required: false
  allele_name_required: true
  allow_expression_change: false
  expression_required: false
- name: accessory
  export_type: accessory
  show_description: false
  description_required: false
  allele_name_required: true
  allow_expression_change: false
  expression_required: false
```

> Only show allele type between parenthesis for accessory' alleles (as per Tuesday's discussion).

I've just committed a change to add a new option "hide_type_name" to fix this.  You would need to add this to the configuration for the "other" allele type:
`hide_type_name: true`

I've changed that setting for flybase-test.
