### ISSUE TITLE
allow ISS annotation in admin mode

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1852]
Curating a paper today with @CuzickA 

There was some bioinformatics analysis demonstrating that  A9JX75_PHANO is a likely chitin binding protein  with various evidences.

We haven't needed to do this in pombase because (almost)  all our ISS's are usually done already in Artemis (in fact we are usually removing them, as EXP evidence becomes avaiable rather them adding them).

That said, once we stop adding  non-experiemntal data in Artemis we will also need this functionality for PomBAse.  

We don't want this available for users because largely we only really  want users to make annotations based on experimental evidence ( @CuzickA  agrees the same for PHIBase too), but occasionally there will be a strongly supported ISS annotation and we can add this in admin mode.

**Comment by kimrutherford** [comment]
I've changed the code to support this.

@jseager7 you'll need to add this to each of the GO annotation types in the canto_deploy.yaml:
```yaml
     admin_evidence_codes:
       - ISS
```

For example:
```yaml
   - name: molecular_function
     category: ontology
     abbreviation: F
     very_short_display_name: 'function'
     short_display_name: 'molecular function'
     display_name: 'GO molecular function'
     feature_type: 'gene'
     can_have_with: 1
     evidence_codes:
       - IDA
       - IGI
       - IMP
       - IPI
       - EXP
     admin_evidence_codes:
       - ISS
...
```
