### ISSUE TITLE
Allow extensions to be restricted to specific annotation types

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2004]
From  #1962:

>I've seen the interaction extensions and they can be selected during the phenotype
> annotation.
> 1 - Would it be possible to disable them at the phenotype annotation stage and only
> allowing them on 'edit' during the interaction annotation stage?

We'll probably need a new column in the configuration file for this.

**Comment by ValWood** [comment]
I don't understant this. Extensions for an annotation type should only be present if they are in the config file?

**Comment by kimrutherford** [comment]
> Extensions for an annotation type should only be present if they are in the config file?

The extensions are configured per ontology and we now use the same ontology for phenotype and interaction annotations.  FlyBase would like to be able to have some phenotype extensions be available only for interaction annotations.  Let's chat about this on Tuesday.

**Comment by jseager7** [comment]
PHI-Canto will probably need this feature too, specifically for issue https://github.com/pombase/canto/issues/2345. Based on previous discussion, `canto_deploy.yaml` might be a better place to configure which extensions are restricted to which annotation types, since that config file already controls which annotation types are enabled globally.

In our case, we're planning to have two mutually-exclusive extensions that should only appear on separate annotation types. The plan is to identify the extensions in the config file by their 'extension relation' column.

We could add the restricted extensions as an additional property of annotations in `available_annotation_type_list`, in which case the extensions listed would be shown only for that annotation type (and hidden for all others). For example:

```yaml
available_annotation_type_list:
  - name: pathogen_host_interaction_phenotype
    restricted_extensions:
    - infective_ability
    # etc...
  - name: gene_for_gene_phenotype
    restricted_extensions:
    - interaction_outcome
    # etc...
```
