### ISSUE TITLE
multi-allele genotypes - order alleles by type other>aberration>accessory

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2189]
Multi-allele genotypes should always show 'other'-type alleles first, then aberrations, then accessories.

Currently, they seem to be ordered alphabetically:
<img width="584" alt="Screen Shot 2020-01-23 at 15 53 28" src="https://user-images.githubusercontent.com/33721108/73000307-93dadf80-3df8-11ea-95dc-b9115ed02b4e.png">

In the second example, the Sema5c allele should come before the Scer\GAL4 allele.

It may seem a cosmetic change but will help a lot the reading of genotypes

**Comment by kimrutherford** [comment]
Hi Vitor.

I've changed the code so that the order of alleles in the genotype display matches the order in the configuration file.

I've changed the configuration on the server to this which should give the order you'd like.  I've swapped aberration and accessory:

```yaml
# configuration of allele types
allele_type_list:
  - name: other
    export_type: other
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    hide_type_name: true
    placeholder: Please provide a description
  - name: aberration
    export_type: aberration
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: false
    expression_required: false
  - name: accessory
    export_type: accessory
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    do_not_annotate: 1
    placeholder: Please provide a description
```

**Comment by vmt25** [comment]
Sounds good.
I'll change my working canto_deploy.yaml accordingly and add a comment to explain that.

**Comment by vmt25** [comment]
(long overdue feedback, but low priority)
The issue persists.
This is not a major issue, though. Otherwise I would have provided feedback long ago.

See the screenshots below. In both of them the default 'other' type allele comes after the aberration allele (1st image) or the accessory allele (2nd image)

<img width="973" alt="Screenshot 2020-06-23 at 10 15 32" src="https://user-images.githubusercontent.com/33721108/85385754-93c34500-b53a-11ea-9501-021ee2a55831.png">


<img width="933" alt="Screenshot 2020-06-23 at 10 10 45" src="https://user-images.githubusercontent.com/33721108/85385526-4f37a980-b53a-11ea-8a44-da75d9c9fbfb.png">

**Comment by vmt25** [comment]
As discussed on the 20th of April VC, this is to remind of this ticket and with some more examples. Apologies if it is too much info or lack of clarity.

In a nutshell, genotypes not always follow the desirable ordering of alleles by type: other > aberration (Df) >accessory. And there is inconsistency between genotypes on the genotype management page, annotations tables and genotype page title.

I feel there isn't an complete pattern that explains why the order of the alleles is what it is. (order of selection on the genotype management page does not explain it; alphanumerical order does not explain it)

**Diploid genotypes with aberrations:**
On genotype management pages genotypes are OK (other/Df), but on the annotations page they (always?) show reversed (Df/other); this pattern is also observed when this type of genotype is part of a complex multi-locus genotype (see https://curation.pombase.org/flybase/curs/413670c638bb7f00/genotype_manage/ro at the bottom of the comment)

https://curation.pombase.org/flybase/curs/c55d1e8b58281f33/ro/ :
<img width="468" alt="Screen Shot 2021-06-11 at 17 18 17" src="https://user-images.githubusercontent.com/33721108/121717444-13924880-cad9-11eb-9885-e1bc986961ca.png">

<img width="783" alt="Screen Shot 2021-06-11 at 17 05 21" src="https://user-images.githubusercontent.com/33721108/121717345-fa899780-cad8-11eb-86d2-abe930b8d603.png">

**Multi-locus genotypes involving one 'other' allele and one 'accessory' allele:**
Seem to be OK on the genotype management but can show wrong on annotations tables and on the genotype page title (does not seem to be alphanumerical or order of selection while building the genotype)


https://curation.pombase.org/flybase/curs/c55d1e8b58281f33/ro/ :


<img width="322" alt="Screen Shot 2021-06-11 at 17 34 58" src="https://user-images.githubusercontent.com/33721108/121720798-679e2c80-cadb-11eb-9a03-084d02f538de.png">


<img width="779" alt="Screen Shot 2021-06-11 at 17 34 44" src="https://user-images.githubusercontent.com/33721108/121720808-6c62e080-cadb-11eb-9c56-f2778770e0e3.png">


<img width="835" alt="Screen Shot 2021-06-14 at 10 57 20" src="https://user-images.githubusercontent.com/33721108/121874566-60576880-ccff-11eb-9eb7-ff5b1364c46f.png">



**Multi-locus genotypes involving at least one diploid and one 'accessory' allele:**
Accessory allele ideally should be at the very bottom but always shows ahead of diploid on genotype management page, annotations tables and the genotype page title. 

https://curation.pombase.org/flybase/curs/413670c638bb7f00/ro :


<img width="484" alt="Screen Shot 2021-06-14 at 11 22 46" src="https://user-images.githubusercontent.com/33721108/121878788-03aa7c80-cd04-11eb-8c18-c0d16b1b365d.png">


<img width="771" alt="Screen Shot 2021-06-14 at 11 33 05" src="https://user-images.githubusercontent.com/33721108/121879097-613ec900-cd04-11eb-8bde-3c62c9cea3bd.png">


**Multi-locus genotypes can show their components inconsistently between annotation table, genotype page title and genotype maangement page**


In the example below, the diploid show first on the genotype page title but shows last on the annotation table. The order should be the same everywhere (with the accessory last and the diploid showing the Df second)

https://curation.pombase.org/flybase/curs/413670c638bb7f00/ro :

<img width="760" alt="Screen Shot 2021-06-14 at 11 38 11" src="https://user-images.githubusercontent.com/33721108/121879872-3bfe8a80-cd05-11eb-93d6-f2e3193c0418.png">


In the example below, the accessory allele shows first in the genotype page title but second on the annotation tables and genotype management page

https://curation.pombase.org/flybase/curs/413670c638bb7f00/ro :

<img width="799" alt="Screen Shot 2021-06-14 at 11 40 52" src="https://user-images.githubusercontent.com/33721108/121880427-e5de1700-cd05-11eb-92e0-7d7a20216228.png">

**Comment by kimrutherford** [comment]
Hi Vitor.

I've had a first attempt at fixing this.  I think I've covered all your points, but please have a look and let me know if it needs further changes.

I've updated the FlyBase Canto with these changes.

**Comment by arzuozturk** [comment]
Hi Kim,

Many thanks for looking into this.
I am not sure whether the changes you've recently made would cover the curation in progress but here is what I see on

https://curation.pombase.org/flybase/curs/67dda7f928e3b259/genotype_manage#/select/19

One accessory allele is on the top of the list, the others are in the middle.

![image](https://user-images.githubusercontent.com/66944690/123963504-71180780-d9aa-11eb-95a8-5cc352aaec3d.png)

The order seems to be okay in

![image](https://user-images.githubusercontent.com/66944690/123963844-c3f1bf00-d9aa-11eb-96c6-7d712e67e603.png)

But not in 

![image](https://user-images.githubusercontent.com/66944690/123963930-d53acb80-d9aa-11eb-811b-f943925038ca.png)

**Comment by arzuozturk** [comment]
Hi Kim,

Thank you for looking into this. Could I also ask you to arrange the order of alleles in "Single-locus genotypes" as aberration>other>accessory, if possible?

Right now, for https://curation.pombase.org/flybase/curs/67dda7f928e3b259/genotype_manage they look like this:
![image](https://user-images.githubusercontent.com/66944690/123974641-ae819280-d9b4-11eb-9c76-7f6db7e9362b.png)

**Comment by vmt25** [comment]
> Hi Kim,
> 
> Thank you for looking into this. Could I also ask you to arrange the order of alleles in "Single-locus genotypes" as aberration>other>accessory, if possible?
> 
> Right now, for https://curation.pombase.org/flybase/curs/67dda7f928e3b259/genotype_manage they look like this:
> ![image](https://user-images.githubusercontent.com/66944690/123974641-ae819280-d9b4-11eb-9c76-7f6db7e9362b.png)

I agree with Arzu that this would be useful, but I think it is only applicable for the haploid genotypes.
Actually, I think it is already set to show aberrations first.

**Comment by vmt25** [comment]
> Hi Vitor.
> 
> I've had a first attempt at fixing this. I think I've covered all your points, but please have a look and let me know if it needs further changes.
> 
> I've updated the FlyBase Canto with these changes.

Hi Kim, it looks like all the issues on my comment from 16 days ago have been addressed. Thanks

**Comment by kimrutherford** [comment]
> Thank you for looking into this. Could I also ask you to arrange the order of alleles in "Single-locus genotypes" as aberration>other>accessory, if possible?

Hi Arzu.  I'll fix that next.

**Comment by kimrutherford** [comment]
> Could I also ask you to arrange the order of alleles in "Single-locus genotypes" as aberration>other>accessory, if possible?

Hi Arzu.  I've made that change.  Could you check that the order is now how you expect?

**Comment by arzuozturk** [comment]
Hi Kim,
It worked for PMID:32792569. Thank you so much!
I will check others and report back to you if I see any problems.

**Comment by vmt25** [comment]
https://curation.pombase.org/flybase/curs/413670c638bb7f00/ has all types of alleles and it orders them as other>aberration>accessory. 
I am fine with that.

**Comment by kimrutherford** [comment]
> it orders them as other>aberration>accessory.
> I am fine with that. 

Sorry, I see that I mis-read Arzu's comment.

Currently the order of the allele types is set in the configuration file and it applies everywhere in Canto.  So it uses the order other>aberration>accessory for the genotype lists and to order the alleles in multi-allele genotypes lists.

If it's better to put the aberrations first in the single allele genotype list, let me know.

The order of the alleles comes from this section of the configuration file:

```yaml
allele_type_list:
  - name: other
    export_type: other
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    hide_type_name: true
    placeholder: Please provide a description
  - name: aberration
    export_type: aberration
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: false
    expression_required: false
  - name: accessory
    export_type: accessory
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    do_not_annotate: 1
    placeholder: Please provide a description
```
