### ISSUE TITLE
Have easy way to create temporary alleles

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2282]
(related to #2281)

Occasionally the identity of an allele is unclear or some allele is missing. In those cases we keep on curating using a temporary/placeholder allele, which we change once we have the required information.
e.g. there are 3 mutant alleles for a given gene, gene X, but the authors only mention 'X mutants'. In these cases we curate to a mock allele, say X[mut??], where the double question marks are a warning/error indicator.

Usually we put those sessions on hold until e.g. the authors reply to us indicating which allele is which for each experiment, hence the relationship to #2281

I have been able to create such temporary allele in a convoluted way (see below) but I wonder whether it could be easier, namely via a extra button on either the 'genotype management' page or on the gene page. The desired format would be 'gene symbol' + [ + temporary description + ?? + ]

What I have been doing is go to the gene page, click on 'Single allele Phenotype class' or 'Single allele Phenotype anatomy' and then create an allele with double question marks

**Comment by ValWood** [comment]
Since this is only temporary anyway maybe you can use the "other"  or "unknown" allele option and 
description temporary?

**Comment by kimrutherford** [comment]
> Since this is only temporary anyway maybe you can use the "other" or "unknown" allele
> option and description temporary?

Or we can add a new allele type, "temporary" which will make them easy to find and easy to warn about if they are in the JSON export file by mistake.

**Comment by vmt25** [comment]
> Or we can add a new allele type, "temporary" which will make them easy to find and easy to warn about if they are in the JSON export file by mistake.

That could work, but it would be useful to have temporary for all of the current allele types: 'other temporary', 'accessory temporary' and 'aberration temporary'.

**Comment by kimrutherford** [comment]
> That could work, but it would be useful to have temporary for all of the current allele types:
> 'other temporary', 'accessory temporary' and 'aberration temporary'.

That's a quick configuration change if you'd like those allele types.

**Comment by vmt25** [comment]
Nice!

**Comment by kimrutherford** [comment]
> That's a quick configuration change if you'd like those allele types.

Should I go ahead and make that change?

The current config is:
```yaml
allele_type_list:
  - name: other
    export_type: other
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    hide_type_name: true
    placeholder: Please provide a description
  - name: aberration
    export_type: aberration
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: false
    expression_required: false
  - name: accessory
    export_type: accessory
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    do_not_annotate: 1
    placeholder: Please provide a description
```

We need to add this to end of the config:
```yaml
  - name: other_temporary
    export_type: other_temporary
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    hide_type_name: true
    placeholder: Please provide a description
  - name: aberration_temporary
    export_type: aberration_temporary
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: false
    expression_required: false
  - name: accessory_temporary
    export_type: accessory_temporary
    show_description: true
    description_required: false
    allele_name_required: false
    allow_expression_change: true
    expression_required: true
    do_not_annotate: 1
    placeholder: Please provide a description
```
