### ISSUE TITLE
Inconsistent behavior of ontology subsets in term autocomplete  

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2584]
We've been noticing some strange behaviour in PHI-Canto's term autocomplete, where terms in one ontology subset are being hidden but other terms (with seemingly identical configuration) are still being shown.

Here's our ontology subset configuration:

```yaml
ontology_namespace_config:
  subsets_to_ignore:
    primary_autocomplete:
      - "is_a(Grouping_terms)"
      - "is_a(qc_do_not_annotate)"
      - "is_a(qc_extension_only)"
    primary_select:
      - "is_a(Grouping_terms)"
      - "is_a(qc_do_not_annotate)"
      - "is_a(qc_extension_only)"
    extension:
      - "is_a(canto_root_subset)"
      - "is_a(qc_do_not_annotate)"
  do_not_annotate_subsets:
    - "is_a(canto_root_subset)"
    - "is_a(qc_do_not_annotate)"
    - "is_a(gocheck_do_not_annotate)"
    - "is_a(gocheck_do_not_manually_annotate)"
```
The `qc_extension_only` subset was added by us, in order to hide terms from the main autocomplete that are only meant to be used in annotation extensions (see https://github.com/PHI-base/phipo/issues/261).

The strange thing is that any terms tagged with `qc_extension_only` don't appear in the term selector, whereas terms tagged with `qc_do_not_annotate` still appear. Here's a `qc_extension_only` example term from the .obo file (only the relevant properties are shown).

```
[Term]
id: PHIPO:0000004
name: unaffected pathogenicity
namespace: pathogen_host_interaction_phenotype
subset: qc_extension_only
is_a: PHIPO:0000006 ! pathogenicity phenotype
```
Here's what appears in the autocomplete:

![image](https://user-images.githubusercontent.com/37659591/172174839-77006ba5-da44-4980-baa5-a59c72069414.png)

And here's the corresponding case for a term tagged as `qc_do_not_annotate`:
```
[Term]
id: PHIPO:0000001
name: pathogen host interaction phenotype
namespace: pathogen_host_interaction_phenotype
subset: qc_do_not_annotate
subset: qc_do_not_manually_annotate
is_a: PHIPO:0000505 ! phenotype
```

![image](https://user-images.githubusercontent.com/37659591/172175211-d1cbf0ff-4eac-4849-8971-d0876248f341.png)

Both the `qc_extension_only` and `qc_do_not_annotate` subsets are in the `primary_autocomplete` and `primary_select` properties in `subsets_to_ignore`, so I'd expect both of the above terms to be hidden. The only difference is that `qc_do_not_annotate` is in `do_not_annotate_subsets` while `qc_extension_only` isn't.

Here's the PomBase subset configuration, for reference:
```yaml
ontology_namespace_config:
  subsets_to_ignore:
    primary:
      - "is_a(Grouping_terms)"
      - "never_in_taxon(NCBITaxon:4896)"
    extension:
      - "is_a(canto_root_subset)"
      - "is_a(qc_do_not_annotate)"
  do_not_annotate_subsets:
    - "is_a(canto_root_subset)"
    - "is_a(qc_do_not_annotate)"
    - "is_a(gocheck_do_not_annotate)"
    - "is_a(gocheck_do_not_manually_annotate)"
```
It looks like this configuration doesn't hide the terms tagged as `qc_do_not_annotate` in the main selector, so does it just prevent the terms from being selected? It also seems to use different property names, so maybe there's been a configuration schema change I'm not aware of.

@kimrutherford Do you think this is a problem with Canto, or with our configuration?

**Comment by kimrutherford** [comment]
Hi @jseager7 

That does seem like a bug.

This is probably is silly question, but have you reloaded the ontologies since you changed configuration?

Could you send me your `track.sqlite3` so I can do some debugging?  Thanks.

**Comment by jseager7** [comment]
> This is probably is silly question, but have you reloaded the ontologies since you changed configuration?

The ontologies reload nightly and I'm sure they've been reloaded (and Canto restarted) since I made this configuration change.

I'll send you a copy of the track database.

**Comment by jseager7** [comment]
I just double-checked the configuration on our servers and realised that the configuration I pasted above is not actually the same configuration that's on our servers. The server configuration is missing `qc_do_not_annotate` under `primary_autocomplete`:
```yaml
ontology_namespace_config:
  subsets_to_ignore:
    primary_autocomplete:
      - "is_a(Grouping_terms)"
      - "is_a(qc_extension_only)"
    primary_select:
      - "is_a(Grouping_terms)"
      - "is_a(qc_do_not_annotate)"
      - "is_a(qc_extension_only)"
    extension:
      - "is_a(canto_root_subset)"
      - "is_a(qc_do_not_annotate)"
  do_not_annotate_subsets:
    - "is_a(canto_root_subset)"
    - "is_a(qc_do_not_annotate)"
    - "is_a(gocheck_do_not_annotate)"
    - "is_a(gocheck_do_not_manually_annotate)"
```
That matches what you were saying about everything working okay when you left `qc_do_not_annotate` where it was, so I guess this is the cause of the problem. I must have had a fix waiting on my local machine that I never pushed. Oops.

Thanks for helping catch my mistake. I'll make this configuration change to our servers and reopen this issue if the problem doesn't go away.
