### ISSUE TITLE
GI overexpression prompts

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2610]
@ValWood @kimrutherford 

The full list of constrains is in this issue: https://github.com/pombase/canto/issues/2593

I think the prompts from Dosage Lethality and Dosage Growth defect would be better if they looked like the prompts in parenthesis here:

![Screenshot 2022-08-24 at 12 16 05](https://user-images.githubusercontent.com/22526102/186405228-eb3bba23-5e67-4962-a94c-10d19edece03.png)

Instead of:
![Screenshot 2022-08-24 at 12 13 25](https://user-images.githubusercontent.com/22526102/186405333-aaaeb360-c3e7-4294-97e6-60e3ac170afa.png)
![Screenshot 2022-08-24 at 12 12 03](https://user-images.githubusercontent.com/22526102/186405338-5fedbb19-3eb2-4591-b516-f7465008aa24.png)

I think they make the directionality more clear. Perhaps the `overexpressed` last word can be removed (to say `inviable in pressence of pkl1[overexpression]` instead of `inviable in pressence of overexpressed pkl1[overexpression]`)

The one from Dosage Rescue is OK, but I would still remind the user that the phenotypes must be growth related, so `lethality or growth defect phenotypes rescued by...`. They may select dosage rescue instead of phenotypic suppression and might be confused not to find the desired phenotypes in there.

![Screenshot 2022-08-24 at 12 12 21](https://user-images.githubusercontent.com/22526102/186405335-863b17e9-64d4-4490-8faf-02dd3a118ccb.png)

**Comment by ValWood** [comment]
The prompt suggestions look good.

**Comment by kimrutherford** [comment]
> I think the prompts from Dosage Lethality and Dosage Growth defect would be better if they looked like the prompts in parenthesis here:

Can we use all of those prompts in the dialog?  It would be simpler if we could.

**Comment by kimrutherford** [comment]
We had a discussion about this a while ago: https://github.com/pombase/canto/issues/2559#issuecomment-1094835283

And a bit here too: https://github.com/pombase/canto/issues/2577

**Comment by ValWood** [comment]
@manulera  can you check that this text works for all prompts. If so it is OK to change.

**Comment by kimrutherford** [comment]
> Hi @kimrutherford. I had a look at canto.yaml, and I made a PR with the prompts as I think they could be 

Do you think this is OK in the test Canto now?

**Comment by manulera** [comment]
Hi @kimrutherford this does not seem to have changed for Dosage Growth defect, at least I can't see the changes:

![Screenshot 2022-09-06 at 09 52 14](https://user-images.githubusercontent.com/22526102/188591751-74e8444b-ae59-49a6-a669-98900dd37c6c.png)

Comes up here:

https://user-images.githubusercontent.com/22526102/188592813-455bc2e2-fe9b-4afa-a121-36b236f84822.mov

**Comment by kimrutherford** [comment]
> I had a look at canto.yaml, and I made a PR with the prompts as I think they could be (mostly the same as the parenthesis) written in the interaction_dialog_type_label 

> this does not seem to have changed for Dosage Growth defect, at least I can't see the changes:

Thanks for making the changes.  I realise now what the problem was.  A few weeks ago I removed the code that uses the `interaction_dialog_type_label` configuration because there were two different setting for the interaction labels.  I forgot to remove the `interaction_dialog_type_label` settings from `canto.yaml`.

Now only the `non_symmetric_interaction_labels`->`interactor_a` config is used.  I've moved your changes to `interactor_a` so they should be visible now.

Here's an example, including one of your fixes:

```yaml
'Dosage Rescue':
  definition: "A genetic interaction is inferred when over expression or increased dosage ..."
  name: 'Dosage Rescue (lethality or growth defect rescued by overexpression of)'
  is_symmetric: 0
  overexpression_implies_direction: 1
  non_symmetric_interaction_labels:
    interactor_a: "lethality or growth defect rescued by overexpression of"
    interactor_b: overexpression rescues
```

Currently the `interactor_b` settings aren't used and aren't up to date so I may remove them soon.
