### ISSUE TITLE
Allow multiple ontologies to be used for one annotation type

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2730]
PHI-Canto has a 'Disease name' annotation type that currently uses terms from a controlled vocabulary (PHIDO) that PHI-base developed themselves, by copying disease names out of the PHI-base database.

However, many of the terms in PHIDO duplicate the semantics of terms from existing disease ontologies (particularly MONDO), so we should really be reusing those existing terms.

The problem is, we can't just use MONDO because it's missing terms for many diseases in PHI-base. 

For human and animal diseases, we can probably just request new terms from MONDO (or from its contributing source ontologies), but plant disease seems to have no representation at all and may be out of scope for MONDO anyway.

The only other ontology related to plant disease that we can find is the Plant Stress Ontology (PSO), but that only has a very general hierarchy of plant diseases (e.g. 'disease of spinach') which aren't even included in the OBO version of the ontology. PSO has seen no further updates since May 2020.

Basically, we'll probably need to use a combination of terms from MONDO and PHIDO for the foreseeable future (maybe plus some extra disease ontologies in future to cover other terms).

The problem is, Canto only seems to filter its ontology terms based on the OBO namespace, so presumably the only way to add MONDO terms to the Disease name annotation type is to inject the 'phido' namespace property into every MONDO term that we want to include.

```yaml
  - name: disease_name
    category: ontology
    namespace: phido
```

I don't think there's anything in the MONDO license (CC BY 4.0) that precludes modifying the terms, and the change will never be exposed to end users since Canto only exports the term ID. Still, this isn't really an elegant solution.

@kimrutherford Can you think of any better solutions to this that wouldn't be prohibitively difficult? Also, is my proposed solution actually feasible?

**Comment by kimrutherford** [comment]
Hi James.

I think your suggestion adding MONDO terms to your OBO file, then adding `namespace: phido` to them to would work.  It's a very reasonable plan.  I've seen that sort of thing in other OBO files.  I don't know how to do that in OWL.

Another option is to have a PHIDO term for each MONDO term that you need to use, with an `xref:` containing the original MONDO ID.  I think that's also a reasonable option and gives you more control that using MONDO terms directly and it means all the disease annotations use the same ontology.  But that's more work than just adding `namespace: phido` to a copy-and-pasted MONDO term.

A third option (which I can't guarantee will work) is to change your `annotation_type` configuration to something like:
```
  - name: disease_name
    category: ontology
    namespace: "[PHIDO:0000001|MONDO:0000001]"
    ...
``` 
The advantage of this plan is that you will (hopefully) allow you to select any term from PHIDO or MONDO, rather than having to add the term to the PHIDO owl or obo file before it can be used.  The downside is that you'll need to load all of MONDO in Canto.

**Comment by jseager7** [comment]
@kimrutherford I've tested the alternative namespace syntax, and unfortunately the terms from MONDO are not suggested, despite being loaded in the database. Only terms from PHIDO appear.

Using 'chronic erythremia' (MONDO:0001394) as an example, here's what appears in the autocomplete:

![image](https://github.com/pombase/canto/assets/37659591/47e20f74-d33f-45d7-8fcc-8b0715a73a34)

The term does appear if the term ID is entered instead:

![image](https://github.com/pombase/canto/assets/37659591/27c75684-2321-4fe8-b430-20aa709fab64)

Looking at the source code, I can't see any special parsing being applied to the `namespace` property to make the pipe-separated syntax work as intended. But if the namespace isn't being parsed correctly, why am I still seeing terms for PHIDO?

Here's the configuration for the disease_name annotation:

```yaml
  - name: disease_name
    category: ontology
    namespace: "[PHIDO:0000001|MONDO:0000001]"
    very_short_display_name: 'disease'
    short_display_name: 'disease'
    display_name: 'disease name'
    synonyms_to_display:
      - exact
    feature_type: 'metagenotype'
    can_have_conditions: 0
    broad_term_suggestions: ""
    specific_term_examples: ""
    help_text:
      Annotate the expected disease for this pathogen-host interaction, where 'expected' refers to the case of a pathogen strain interacting with a host strain with no experimentally-induced mutations, and where the interaction between the pathogen and the host is compatible (i.e. the interaction results in disease).
    more_help_text: ~
    extra_help_text: ~
    detailed_help_path: /docs/disease_annotation
```
