### ISSUE TITLE
Strain-to-species mapping doesn't affect already added organisms

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2831]
The strain-to-species mapping that PHI-Canto does for NCBI Taxonomy IDs doesn't seem to apply to organisms that have already been added to a curation session.

I was trying to remap the strain-level ID Aspergillus oryzae (strain ATCC 42149 / RIB 40) [510516] to the species-level ID for Aspergillus oryzae [5062]. I added the configuration to species_strain_map.yaml:
```yaml
  5062:
    reference_strain: 5062
    other_strains:
      - 90341
      - 301529
      - 332754
      - 510516  # strain-level ID
```

But the strain-level organism was not updated in the curation session after restarting Canto:

![image](https://github.com/pombase/canto/assets/37659591/da4092e9-068e-443c-a898-d26169a9e523)

The session database still has the strain-level taxonomy ID in it.

I can't find where in the code the species-to-strain remapping is meant to happen, but I'm guessing it takes place when the organism is first loaded or when the session is first created.

@kimrutherford Please can you point me in the right direction?
